### ISSUE TITLE
Palmetto.py got a syntax errors.!

### ISSUE THREAD

**Issue by mkumatag** [openbmc/skeleton#40]
root@palmetto:/etc/systemd/system/multi-user.target.wants# systemctl  status skeleton.service
● skeleton.service - Temp placeholder for skeleton function
   Loaded: loaded (/lib/systemd/system/skeleton.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Tue 2016-02-02 09:06:14 UTC; 14min ago
  Process: 885 ExecStart=/usr/sbin/system_manager.py Palmetto (code=exited, status=1/FAILURE)
 Main PID: 885 (code=exited, status=1/FAILURE)

Feb 02 09:06:13 palmetto system_manager.py[885]: Traceback (most recent call last):
Feb 02 09:06:13 palmetto system_manager.py[885]: File "/usr/sbin/system_manager.py", line 18, in <module>
Feb 02 09:06:13 palmetto system_manager.py[885]: System = **import**(sys.argv[1])
Feb 02 09:06:13 palmetto system_manager.py[885]: File "/usr/sbin/Palmetto.py", line 152
Feb 02 09:06:13 palmetto system_manager.py[885]: 'bmc_control' : {
Feb 02 09:06:13 palmetto system_manager.py[885]: ^
Feb 02 09:06:13 palmetto system_manager.py[885]: SyntaxError: invalid syntax
Feb 02 09:06:14 palmetto systemd[1]: skeleton.service: Main process exited, code=exited, status=1/FAILURE
Feb 02 09:06:14 palmetto systemd[1]: skeleton.service: Unit entered failed state.
Feb 02 09:06:14 palmetto systemd[1]: skeleton.service: Failed with result 'exit-code'.
Hint: Some lines were ellipsized, use -l to show in full.
root@palmetto:/etc/systemd/system/multi-user.target.wants#

**Comment by mkumatag** [comment]
submitted fix in PR - https://github.com/openbmc/skeleton/pull/41
